//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatasetClearence
    {
        public int ID { get; set; }
        public Nullable<int> ClearenceID { get; set; }
        public Nullable<int> DatasetID { get; set; }
    
        public virtual Clearence Clearence { get; set; }
        public virtual Dataset Dataset { get; set; }
    }
}
