//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clearence> Clearences { get; set; }
        public virtual DbSet<DatasetClearence> DatasetClearences { get; set; }
        public virtual DbSet<Dataset> Datasets { get; set; }
        public virtual DbSet<UserClearence> UserClearences { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
